In [1]:
import numpy as np

m = 4
n = 5

mat = np.array([
    [1.2, 3.5, 5.7, 2.1, 4.4],
    [6.8, 2.4, 3.6, 8.7, 5.9],
    [4.3, 7.1, 8.2, 1.4, 3.7],
    [9.8, 2.1, 4.5, 6.2, 7.0]
])

mat_t = mat.T

cov_mat = np.cov(mat_t, rowvar=False)

corr_mat = np.corrcoef(mat_t, rowvar=False)

print('Matrix (4x5):\n', mat, '\n')
print('Covariance Matrix (5x5):\n', cov_mat, '\n')
print('Correlation Matrix (5x5):\n', corr_mat, '\n')


Matrix (4x5):
 [[1.2 3.5 5.7 2.1 4.4]
 [6.8 2.4 3.6 8.7 5.9]
 [4.3 7.1 8.2 1.4 3.7]
 [9.8 2.1 4.5 6.2 7. ]] 

Covariance Matrix (5x5):
 [[ 3.207  -2.8255  3.121  -2.867 ]
 [-2.8255  6.327  -6.3865  5.228 ]
 [ 3.121  -6.3865  7.443  -4.4235]
 [-2.867   5.228  -4.4235  8.227 ]] 

Correlation Matrix (5x5):
 [[ 1.         -0.62725902  0.6388079  -0.5581584 ]
 [-0.62725902  1.         -0.93065773  0.72462934]
 [ 0.6388079  -0.93065773  1.         -0.56528996]
 [-0.5581584   0.72462934 -0.56528996  1.        ]] 

